command_timeout = 1000

[aws]
format = ""

[directory]
truncate_to_repo = false
truncation_length = -1
style = "fg:bright-green"

[username]
show_always = true
style_root = "bold fg:bright-blue"
style_user = "bold fg:bright-blue"

[git_branch]
format = "[$symbol$branch]($style) "
style = "fg:bright-yellow"

[line_break]
disabled = false

[time]
disabled = false
format = '🕙[ $time ]($style)'
time_format = "%R"

[git_status]
ahead = "⇡${count}"
diverged = "⇡${ahead_count} ⇣${behind_count}"
behind = "⇣${count}"
conflicted = "[🤪 ${count}](bright-red) "
untracked = "🤷 ‍${count} "
stashed = "[📦 ${count}](bright-blue) "
modified = "[📒 ${count}](yellow) "
staged = "[✔ ${count}](green) "
renamed = "[🚗 ${count}](bright-red) "
deleted = "[🗑 ${count}](red) "

[git_commit]
only_detached = false

[java]
disabled = true

[package]
disabled = true
